import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import Providers from '@/library/Provider/Providers';
import { ThemeProvider } from '@mui/material';
import { theme } from '@/library/Themes/theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <ThemeProvider theme={theme}>
        <html lang="en">
          <body className={inter.className}>
            <Toaster position="bottom-center" />
            {children}
          </body>
        </html>
      </ThemeProvider>
    </Providers>
  );
}
